services:
  microservice1:
    container_name: NutriData
    build: ./nutriData
    volumes:
      - ./nutriData/src:/usr/src/app
    networks:
      - sincarne
    ports:
      - "3010:3010"
  microservice2:
    container_name: UserProfile
    build: ./userProfile
    volumes:
      - ./userProfile/src:/usr/src/app
    networks:
      - sincarne
    ports:
      - "3011:3011"
  api-gateway:
    container_name: api-gateway
    build: ./apigateway
    volumes:
      - ./apigateway/src:/usr/src/app
    networks:
      - sincarne
    ports:
      - "3000:3000"
networks:
  sincarne:
    driver: bridge